### ISSUE TITLE
Document server fails with "./x2t: Permission denied"

### ISSUE THREAD

**Issue by Xeyk** [nextcloud/documentserver_community#10]
Hey, all. I have updated my Nextcloud instance from 16 to 18. I uninstalled the OnlyOffice app, then reinstalled it. After doing that, I installed the Community Document Server app. Whenever I click on a .doc or .docx file, I get the error stated in the subject. 

Please let me know if you need me to pull any logs and I will gladly do so.

**Comment by florian-obradovic** [comment]
Same here, updated from 17>18

**Comment by tgurr** [comment]
I got the same error and for me it was a permission problem, installed the app from within Nextcloud, I had the following in the logs:

`Error	documentserver_community	OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: Permission denied`

Which was fixed by:
```
$ cd /var/www/vhost.server.domain/htdocs/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/
$ chmod u+x docbuilder x2t
```

**Comment by poVoq** [comment]
Same with the official 18.0.0RC2-apache Docker image.

**Comment by HackintoshHD** [comment]
Thank you, @tgurr - I had similar errors in my logs when I tried to launch a newly installed OnlyOffice Community Edition of Nextcloud 18 and I can confirm a `chmod u+x docbuilder x2t` in `apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/` fixes that.

**Comment by Xeyk** [comment]
@tgurr Thank you, this got me closer to a solution.

However, when I input this, it switched from a "Permission Denied" error to an "x2t not found" error.. Strangest thing. I am running my installation through docker, which may be the difference.

**Comment by florian-obradovic** [comment]
`cd /var/www/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/
chmod u+x docbuilder x2t`
fixes the error "OCA\DocumentServer\Document\DocumentConversionException: sh: 1: ./x2t: Permission denied"
![image](https://user-images.githubusercontent.com/57985125/72661905-59c8a280-39e0-11ea-99d0-bf67da6e996f.png)

But it doesn't fix the main issue "Community document server is not supported for this instance, please setup and configure an external document server"

**Comment by xorbital** [comment]
I fixed it by:

1. Deactivating and uninstalling OnlyOffice and the document server
2. Reinstalling OnlyOffice
3. Reinstalling Document Server
4. Applying the chmod fix by @tgurr

**Comment by emasty** [comment]
It fixed the permission denied log-entry but not the the "not supported" issue.
I also tried the solution @xorbital suggested.

I am running the official nextcloud:latest docker container behind a reverse proxy. Could that be an issue? There is a entry in the onlyoffice settings called "Service address" for the documentserver. The reverse proxy does forward that address to the docker container but I don't know if the docker image handles that correctly. On the other hand, the "permission denied" log entry shouldn't occur if the documentserver could not be accessed...

**Comment by molle100** [comment]
Thanks, but how can I realize the fix if my NC is running with a Webhoster: Where do I have to go and enter this?
$ cd/var/www/vhost.server.domain/htdocs/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/
$ chmod u+x docbuilder x2t

Is it likely that there will be an update vor the apps that solve the problem without manually fixing it?

**Comment by autoize** [comment]
> Thank you, @tgurr - I had similar errors in my logs when I tried to launch a newly installed OnlyOffice Community Edition of Nextcloud 18 and I can confirm a `chmod u+x docbuilder x2t` in `apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/` fixes that.

Same, after changing the permissions of the x2t file based on @tgurr and @xorbital 's advice, OnlyOffice hangs at with spinning wheel with "document loading" and there's a permission denied message in the NextCloud log. 
```

OCA\DocumentServer\Document\DocumentConversionException: Couldn't create temp folder

    /var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php - line 123:

    OCA\DocumentServer\Document\ConverterBinary->run("/tmp/oc_tmp_BdvSqm-.xml")

    /var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php - line 111:

    OCA\DocumentServer\DocumentConverter->runCommand(OCA\Document ... {})

    /var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php - line 47:

    OCA\DocumentServer\DocumentConverter->convertFiles("/tmp/oc_tmp_gb80zv-.odt", "/var/www/ne ... n")

    /var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php - line 108:

    OCA\DocumentServer\DocumentConverter->getEditorBinary(null, "odt", "/var/www/ne ... 3")

    /var/www/nextcloud/apps/documentserver_community/lib/XHRCommand/AuthCommand.php - line 141:

    OCA\DocumentServer\Document\DocumentStore->getDocumentForEditor(1844461423, OC\Files\Node\File {}, "odt")

    /var/www/nextcloud/apps/documentserver_community/lib/XHRCommand/CommandDispatcher.php - line 45:

    OCA\DocumentServer\XHRCommand\AuthCommand->handle({ type: "aut ... }}, OCA\Document ... {}, OCA\Document ... {}, OCA\Document ... {}, OCA\Document ... {})

    /var/www/nextcloud/apps/documentserver_community/lib/Channel/Channel.php - line 106:

    OCA\DocumentServer\XHRCommand\CommandDispatcher->handle({ type: "aut ... }}, OCA\Document ... {}, OCA\Document ... {}, OCA\Document ... {})

    /var/www/nextcloud/apps/documentserver_community/lib/Controller/SessionController.php - line 114:

    OCA\DocumentServer\Channel\Channel->handleCommand({ type: "aut ... }})

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\DocumentServer\Controller\SessionController->xhrSend(null, "1844461423", "425", "juzazk5i")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Document ... {}, "xhrSend")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 125:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Document ... {}, "xhrSend")

    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Docume ... r", "xhrSend", OC\AppFramew ... {}, { documentId ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ documentId ... "})

    /var/www/nextcloud/lib/private/Route/Router.php - line 299:

    call_user_func(OC\AppFramew ... {}, { documentId ... "})

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/docum ... d")

    /var/www/nextcloud/index.php - line 38:

    OC::handleRequest()
```

**Comment by Marcwa19197** [comment]
I got exactly the same issue.
I updated manually (Downloading ZIP, copying old config.php and run occ upgrade) from NC 17 (latest patchlevel) to NC 18.

I installed the Community Document Server App (which i did not found in any officlal documentation) and installed ONLYOFFICE-App.

I even tried the permission fix by @tgurr without success. I'm still getting the errormessage "Community document server is not supported for this instance, please setup and configure an external document server"

**Comment by PenguinJuice** [comment]
For CentOS or any selinux distro:
cd /var/www/html/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/
chmod u+x docbuilder x2t
ausearch -c 'x2t' --raw | audit2allow -M my-x2t
semodule -i my-x2t.pp

**Comment by PenguinJuice** [comment]
> $ cd /var/www/vhost.server.domain/htdocs/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/
> $ chmod u+x docbuilder x2t
> ```

For selinux do as root in addition to above

ausearch -c 'x2t' --raw | audit2allow -M my-x2t
semodule -i my-x2t.pp

**Comment by NiTRoeSE** [comment]
Same problem here.. the "chmod fix" fixes only the error message but not the`  "Community document server is not supported for this instance, please setup and configure an external document server"`
message.

I also deleted and reinstalled both apps, but ist didnt help. Same config runs fine in NC18 RC2..thats strange. I also have done  a manual upgrade from NC18 RC2 to NC18.

OS: Centos7 x64

**Comment by edwardscaleb9** [comment]
Same issue here.  I manually upgraded from 17.0.1 to 18.0.0, installed ONLYOFFICE then Community Document Server, ran the chmod fix.  I'm running NextCloud behind a Citrix Netscaler doing SSL offloading.

**Comment by xthursdayx** [comment]
I'm having this same problem, and unfortunately the solution posted by @tgurr didn't work for me.

I'm also seeing these seemingly related issues in my logs:

```
[no app in context] Error: OCP\AutoloadNotAllowedException: Autoload path not allowed: /config/www/nextcloud/apps/onlyoffice/lib/appconfig.php at <<closure>>

 0. /config/www/nextcloud/lib/autoloader.php line 164
    OC\Autoloader->isValidPath("/config/www/nex ... p")
 1. <<closure>>
    OC\Autoloader->load("OCA\\Onlyoffice\\AppConfig")
 2. /config/www/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php line 70
    spl_autoload_call("OCA\\Onlyoffice\\AppConfig")
 3. /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\DocumentServer\AppInfo\Application->OCA\DocumentServer\AppInfo\{closure}("*** sensitive parameters replaced ***")
 4. /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 113
    Pimple\Container->offsetGet("OCA\\DocumentSe ... g")
 5. /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 408
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\DocumentSe ... g")
 6. /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 386
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\DocumentSe ... g")
 7. /config/www/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php line 84
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\DocumentSe ... g")
 8. /config/www/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php line 88
    OCA\DocumentServer\AppInfo\Application->getAutoConfig()
 9. /config/www/nextcloud/apps/documentserver_community/appinfo/app.php line 4
    OCA\DocumentServer\AppInfo\Application->register()
10. /config/www/nextcloud/lib/private/legacy/app.php line 265
    require_once("/config/www/nex ... p")
11. /config/www/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("documentserver_community")
12. /config/www/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("documentserver_community")
13. /config/www/nextcloud/lib/base.php line 993
    OC_App::loadApps()
14. /config/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /apps/files
from 172.19.0.1 by xthursdayx at 2020-01-19T00:38:35+00:00
```
and
```
[no app in context] Error: Error: Class 'OCA\Onlyoffice\AppConfig' not found at <<closure>>

 0. /config/www/nextcloud/lib/private/ServerContainer.php line 107
    OCA\Onlyoffice\AppInfo\Application->__construct()
 1. /config/www/nextcloud/lib/private/ServerContainer.php line 133
    OC\ServerContainer->getAppContainer("onlyoffice", "Onlyoffice")
 2. /config/www/nextcloud/apps/onlyoffice/appinfo/app.php line 32
    OC\ServerContainer->query("OCA\\Onlyoffice\\AppInfo\\Application")
 3. /config/www/nextcloud/lib/private/legacy/app.php line 265
    require_once("/config/www/nex ... p")
 4. /config/www/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("onlyoffice")
 5. /config/www/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("onlyoffice")
 6. /config/www/nextcloud/lib/private/legacy/util.php line 197
    OC_App::loadApps(["filesystem"])
 7. /config/www/nextcloud/lib/private/Files/Filesystem.php line 267
    OC_Util::setupFS("")
 8. /config/www/nextcloud/lib/private/Server.php line 319
    OC\Files\Filesystem::getMountManager(null)
 9. /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OC\Server->OC\{closure}("*** sensitive parameters replaced ***")
10. /config/www/nextcloud/lib/private/ServerContainer.php line 125
    Pimple\Container->offsetGet("RootFolder")
11. /config/www/nextcloud/lib/private/Server.php line 341
    OC\ServerContainer->query("RootFolder")
12. <<closure>>
    OC\Server->OC\{closure}("*** sensitive parameters replaced ***")
13. /config/www/nextcloud/lib/private/Files/Node/LazyRoot.php line 62
    call_user_func(Closure {})
14. /config/www/nextcloud/lib/private/Files/Node/LazyRoot.php line 142
    OC\Files\Node\LazyRoot->__call("get", ["__groupfolders"])
15. /config/www/nextcloud/apps/groupfolders/lib/AppInfo/Application.php line 55
    OC\Files\Node\LazyRoot->get("__groupfolders")
16. /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}("*** sensitive parameters replaced ***")
17. /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 113
    Pimple\Container->offsetGet("GroupAppFolder")
18. /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 408
    OC\AppFramework\Utility\SimpleContainer->query("GroupAppFolder")
19. /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 386
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("GroupAppFolder")
20. /config/www/nextcloud/apps/groupfolders/lib/AppInfo/Application.php line 89
    OC\AppFramework\DependencyInjection\DIContainer->query("GroupAppFolder")
21. /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}("*** sensitive parameters replaced ***")
22. /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 113
    Pimple\Container->offsetGet("OCA\\GroupFolde ... d")
23. /config/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 408
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\GroupFolde ... d")
24. /config/www/nextcloud/lib/private/ServerContainer.php line 134
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\GroupFolde ... d")
25. /config/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php line 123
    OC\ServerContainer->query("OCA\\GroupFolde ... d")
26. /config/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php line 104
    OCA\Files_Versions\AppInfo\Application->loadBackend({@attributes: {f ... "})
27. /config/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php line 82
    OCA\Files_Versions\AppInfo\Application->registerVersionBackends()
28. /config/www/nextcloud/lib/private/ServerContainer.php line 107
    OCA\Files_Versions\AppInfo\Application->__construct()
29. /config/www/nextcloud/lib/private/ServerContainer.php line 133
    OC\ServerContainer->getAppContainer("files_versions", "Files_Versions")
30. /config/www/nextcloud/apps/files_versions/appinfo/app.php line 24
    OC\ServerContainer->query("OCA\\Files_Vers ... n")
31. /config/www/nextcloud/lib/private/legacy/app.php line 265
    require_once("/config/www/nex ... p")
32. /config/www/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("files_versions")
33. /config/www/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("files_versions")
34. /config/www/nextcloud/apps/dav/appinfo/app.php line 35
    OC_App::loadApps(["dav"])
35. /config/www/nextcloud/lib/private/legacy/app.php line 265
    require_once("/config/www/nex ... p")
36. /config/www/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("dav")
37. /config/www/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("dav")
38. /config/www/nextcloud/lib/base.php line 993
    OC_App::loadApps()
39. /config/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /apps/files
from 172.19.0.1 by xthursdayx at 2020-01-19T00:11:36+00:00
```
Any ideas?

**Comment by icewind1991** [comment]
0.1.2 should fix most of the "permission denied" errors.

For the sake of keeping the overview, if you're getting "Community document server not supported" errors with different causes in the log, please open a separate issue.

**Comment by Marcwa19197** [comment]
> 0.1.2 should fix most of the "permission denied" errors.
> 
> For the sake of keeping the overview, if you're getting "Community document server not supported" errors with different causes in the log, please open a separate issue.

It also fixed the "Community document server is not supported for this instance, please setup and configure an external document server" error for me! Nice!

**Comment by NiTRoeSE** [comment]
> 0.1.2 should fix most of the "permission denied" errors.
> 
> For the sake of keeping the overview, if you're getting "Community document server not supported" errors with different causes in the log, please open a separate issue.

confirmed, version 0.1.2 works for me. :) thanks!

**Comment by xthursdayx** [comment]
Unfortunately I'm still getting the "Community document server is not supported for this instance, please setup and configure an external document server" error, but there are not any entires in my log, even with debug enabled.  Any ideas where I should start trouble shooting?

**Comment by NiTRoeSE** [comment]
> Unfortunately I'm still getting the "Community document server is not supported for this instance, please setup and configure an external document server" error, but there are not any entires in my log, even with debug enabled. Any ideas where I should start trouble shooting?

Was the same for me... upgrading document server to version 0.1.2 fixed it for me. Maybe its useful to restart webserver and deleting your browser cache... and/or deactivate and delete onlyoffice app and reinstall it after you have upgraded document-server app.

**Comment by poVoq** [comment]
You might also have to click the save button in the OO connector app at least once even if not changing anything?

**Comment by florian-obradovic** [comment]
Fixed with current version for me as well. Thx a lot for the fast fix!

**Comment by polandy** [comment]
For me the `Community Document Server` upgrade to `0.1.2` fixed it! Awesome, thx a lot!

**Comment by ostasevych** [comment]
I fixed my issues by upgrading glibc to 2.14+, what is required by the document server, so, please, check. 

However, I found that chat functionality in the document server is not working: whenever I am typing is not appearing in the chat window.

![image](https://user-images.githubusercontent.com/5199030/72732383-4105eb80-3b9e-11ea-8f6c-f0883f126687.png)

**Comment by Xeyk** [comment]
Unfortunately, upgrading to glibc 2.30 didn't work for me. I actually had to install it since I am running the Linuxserver.io version of Nextcloud which uses Alpine linux's musl libc. I think the installation worked as I got a new error stating 

>  ./x2t: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory 

I installed libstdx++6 which worked successfully, now I am back to the same message ""Community document server is not supported for this instance" However, no new error messages in the log are coming up.

**Comment by xthursdayx** [comment]
> Unfortunately, upgrading to glibc 2.30 didn't work for me. I actually had to install it since I am running the Linuxserver.io version of Nextcloud which uses Alpine linux's musl libc. I think the installation worked as I got a new error stating
> 
> > ./x2t: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
> 
> I installed libstdc++6 which worked successfully, now I am back to the same message ""Community document server is not supported for this instance" However, no new error messages in the log are coming up.

I'm also running the Linuxserver Nextcloud container, so perhaps that has something to do with it? Anyway, please do update here if you find a solution.

**Comment by GreySyntax** [comment]
Summarising the issue on: linuxserver/docker-nextcloud#128
 Looking at the build process for this plugin it is currently extracting large parts of the onlyoffice/documentserver image. The version being extracted seems to only be x86-64 (won’t work on arm,ppc,etc). And the image itself is based on Ubuntu and installs the relevant deb package. This issue will likely be faced with any native binaries in the plugin.

It would probably be best if nextcloud shipped fat versions of native binaries to support multiple platforms and statically linked any dependencies to ensure they are portable across distros.

**Comment by thelamer** [comment]
Linuxserver team member here , you cannot just grab dynamically linked bins and distribute them . They are not portable. 

You can however pass static flags at compile time to embed all needed libs and c toolchain to make them portable. 
Actually programming in a message about the binary not being compatible with the platform it is being run on shows to me that you have a large disconnect between your infra/build people and your front end people. 

Please let me know if you have any questions , I am glad to help.

**Comment by GreySyntax** [comment]
Looking into onlyoffice it seems they only officially target x86-64 (some old success stories of cross compiling to other archs). I’ll try and work out the build system and see how easy it is to create a statically linked binary sometime over the next few days.

**Comment by asteinmetzler** [comment]
Just to add to the discussion - the document server is x86-64 *only* - interesting enough those binaries get also installed on the ARM platform. Below the output from a rPI4 running latest Nextcloud Docker image with activated the community document server app.

```
root@48cf63bfbeb2:/var/www/html/custom_apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin# file docbuilder 
docbuilder: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=d21e8e3e2bbc9ee69bed5dd4680f972424fecb4f, stripped
root@48cf63bfbeb2:/var/www/html/custom_apps/documentserver_community/3rdparty/onlyoffice/documentserver/server
```
```
root@48cf63bfbeb2:/var/www/html/custom_apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin# file x2t 
x2t: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=702ce357ba48aa06b820eba41081d1a5a83ff39b, stripped
root@48cf63bfbeb2:/var/www/html/custom_apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin#
```

This app should be disabled on other architecture ...

**Comment by Phoara** [comment]
I'm still getting the "" error on my Synology NAS. It's a x86-64 CPU, I installed the latest version of the documentserver and I changed the permissions as described above. The error is shown, if I try to open a document, however there's nothing coming up in the Nextcloud logs.

**Comment by buzter** [comment]
> I'm still getting the "Community document server is not supported for this instance, please setup and configure an external document server" error on my Synology NAS. It's a x86-64 CPU, I installed the latest version of the documentserver and I changed the permissions as described above. The error is shown, if I try to open a document, however there's nothing coming up in the Nextcloud logs.
> 
> Edit: I get the same error when I deactivate the community server. Could there be a problem concerning the linking of both Onlyoffice and the document server?

Same here on a Synology NAS. I have no more idea at this moment.

**Comment by dasunsrule32** [comment]
So after stumbling around a lot and finally getting it installed, I also found out this is my issue as well. I'm doing webhosting and the host is CentOS with the following GLIBC installed.
```
rpm -qa|grep -i glibc
glibc-devel-2.12-1.212.el6_10.3.x86_64
glibc-headers-2.12-1.212.el6_10.3.x86_64
glibc-static-2.12-1.212.el6_10.3.x86_64
glibc-2.12-1.212.el6_10.3.i686
glibc-2.12-1.212.el6_10.3.x86_64
glibc-common-2.12-1.212.el6_10.3.x86_64
```

It would be nice if this could be made more portable in the next version. It's really the only thing left that isn't working for me and I'd really like to free my self from Google, O365, etc.

Anyway, here is the log as well:

```
{"reqId":"XiqVo7U97HhU8tMciyjfEwAAABk","level":3,"time":"2020-01-24T06:58:44+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"admin","app":"documentserver_community","method":"GET","url":"/apps/documentserver_community/web-apps/apps/api/documents/api.js","message":
{"Exception":"OCA\\DocumentServer\\Document\\DocumentConversionException","Message":"./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by
  ./x2t)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libkernel.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by 
  ./libkernel.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libgraphics.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libPdfWriter.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by 
  ./libdoctrenderer.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libdoctrenderer.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libHtmlRenderer.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libPdfReader.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libDjVuFile.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libXpsFile.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libHtmlFile.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libUnicodeConverter.so)\n./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by 
  ./libicuuc.so.58)\n","Code":0,"Trace":[
 {"file":"/home1/cz6fqucz/cloud.domain.co/apps/documentserver_community/lib/Document/ConverterBinary.php","line":64,"function":"run","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":[""]},
{"file":"/home1/cz6fqucz/cloud.domain.co/apps/documentserver_community/lib/Controller/StaticController.php","line":90,"function":"test","class":"OCA\\DocumentServer\\Document\\ConverterBinary","type":"->","args":[]},
{"file":"/home1/cz6fqucz/cloud.domain.co/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"webApps","class":"OCA\\DocumentServer\\Controller\\StaticController","type":"->","args":["apps/api/documents/api.js"]},
{"file":"/home1/cz6fqucz/cloud.domain.co/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},
{"file":"/home1/cz6fqucz/cloud.domain.co/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\StaticController"},"webApps"]},
{"file":"/home1/cz6fqucz/cloud.domain.co/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\StaticController","webApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},
{"file":"/home1/cz6fqucz/cloud.domain.co/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"path":"apps/api/documents/api.js","_route":"documentserver_community.Static.webApps"}]},
{"file":"/home1/cz6fqucz/cloud.domain.co/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/web-apps/apps/api/documents/api.js"]},
{"file":"/home1/cz6fqucz/cloud.domain.co/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/home1/cz6fqucz/cloud.domain.co/apps/documentserver_community/lib/Document/ConverterBinary.php","Line":56,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36","version":"18.0.0.10"}
```

and an dependency output:

```
ldd x2t
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./x2t)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libkernel.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./libkernel.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libgraphics.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libPdfWriter.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./libdoctrenderer.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libdoctrenderer.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libHtmlRenderer.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libPdfReader.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libDjVuFile.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libXpsFile.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libHtmlFile.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libUnicodeConverter.so)
./x2t: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libicuuc.so.58)
        linux-vdso.so.1 =>  (0x00007fff4b747000)
        libkernel.so => ./libkernel.so (0x00007fee95365000)
        libgraphics.so => ./libgraphics.so (0x00007fee94b57000)
        libPdfWriter.so => ./libPdfWriter.so (0x00007fee945f3000)
        libdoctrenderer.so => ./libdoctrenderer.so (0x00007fee933f7000)
        libHtmlRenderer.so => ./libHtmlRenderer.so (0x00007fee931c2000)
        libPdfReader.so => ./libPdfReader.so (0x00007fee92b6a000)
        libDjVuFile.so => ./libDjVuFile.so (0x00007fee9282f000)
        libXpsFile.so => ./libXpsFile.so (0x00007fee925f5000)
        libHtmlFile.so => ./libHtmlFile.so (0x00007fee923d8000)
        libUnicodeConverter.so => ./libUnicodeConverter.so (0x00007fee9218c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fee91f6f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fee91ceb000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fee91957000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fee95786000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fee91651000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fee9143b000)
        libicuuc.so.58 => ./libicuuc.so.58 (0x00007fee91075000)
        libicudata.so.58 => ./libicudata.so.58 (0x00007fee8f575000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fee8f371000)
```
```
ldd docbuilder
./docbuilder: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./docbuilder)
./docbuilder: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libkernel.so)
./docbuilder: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./libkernel.so)
./docbuilder: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./libdoctrenderer.so)
./docbuilder: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libdoctrenderer.so)
./docbuilder: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libUnicodeConverter.so)
./docbuilder: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libgraphics.so)
./docbuilder: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libicuuc.so.58)
        linux-vdso.so.1 =>  (0x00007fff6d7f6000)
        libkernel.so => ./libkernel.so (0x00007f0a523b4000)
        libdoctrenderer.so => ./libdoctrenderer.so (0x00007f0a511b8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0a50e24000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0a50c07000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f0a50983000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0a527d5000)
        libUnicodeConverter.so => ./libUnicodeConverter.so (0x00007f0a50737000)
        libgraphics.so => ./libgraphics.so (0x00007f0a4ff29000)
        libicuuc.so.58 => ./libicuuc.so.58 (0x00007f0a4fb63000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f0a4f85d000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f0a4f647000)
        libicudata.so.58 => ./libicudata.so.58 (0x00007f0a4db47000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0a4d943000)
```

**Comment by icewind1991** [comment]
0.1.3 includes a number of checks to show more detailed error messages for known limitations

**Comment by xthursdayx** [comment]
I just tried reinstalling both OnlyOffice and the Community Document server, but I am still unable to open documents. I am now also getting these error, which seems to be related:

```
[PHP] Error: stream_get_contents(): supplied resource is not a valid stream resource at /config/www/nextcloud/apps/documentserver_community/lib/Document/FontManager.php#63

POST /settings/apps/enable
from 172.19.0.1 by xthursdayx at 2020-01-24T19:13:15+00:00
```
and 

```
[PHP] Error: fclose(): supplied resource is not a valid stream resource at /config/www/nextcloud/apps/documentserver_community/lib/Document/FontManager.php#62

POST /settings/apps/enable
from 172.19.0.1 by xthurdayx at 2020-01-24T19:13:15+00:00
```

**Comment by fthl** [comment]
Similar here but not identical:

```
[PHP] Error: stream_get_contents(): supplied resource is not a valid stream resource at /web/nextcloud/apps/documentserver_community/lib/SetupCheck.php#76

GET /nextcloud/index.phpmentserver_community/web-apps/apps/api/documents/api.js
from 88.75.26.157 by admin at 2020-01-24T19:54:35+00:00
```

**Comment by anatomism** [comment]
> > $ cd /var/www/vhost.server.domain/htdocs/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/
> > $ chmod u+x docbuilder x2t
> 
> For CentOS, RedHat & selinux distro do as root in addition to above
> 
> setsebool -P httpd_unified 1
> ausearch -c 'x2t' --raw | audit2allow -M my-x2t
> semodule -i my-x2t.pp

This fixed it for me running CentOS 7, DocServer 0.1.3.

Maybe the SEManage rules should be added to 0.1.4 for good measure for anyone on Cent/RHEL.  It's beyond my capabilities I'm afraid. @icewind1991

**Comment by wuast94** [comment]
> Similar here but not identical:
> 
> ```
> [PHP] Error: stream_get_contents(): supplied resource is not a valid stream resource at /web/nextcloud/apps/documentserver_community/lib/SetupCheck.php#76
> 
> GET /nextcloud/index.phpmentserver_community/web-apps/apps/api/documents/api.js
> from 88.75.26.157 by admin at 2020-01-24T19:54:35+00:00
> ```

i have the same error with "OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: not found"

and i am using the linuxserver docker too. 

will there be a fix or a workaround for that ?

**Comment by Tomas-Mrazek** [comment]
0.1.2 didn't resolve the issue for me,

I'm using official Nextcloud docker image (nextcloud:fpm-alpine)

**Comment by thelamer** [comment]
Yeah Alpine is muslc none of these glibc bins will ever work in ours (linuxserver) or their Alpine flavor. 

I get that compiling the whole codebase for document server is a large task especially considering the associative deps, qt stack, and very controlled build env ( I think they are still on Xenial ) but if you are gonna include this bin as a default plugin you have to do more than ripping it out of their docker image and hoping it works with the libs you have installed sys level . 

We need a build process for this bin with stripped down source code to support it downstream.

**Comment by xthursdayx** [comment]
I've already mentioned this in a comment on issue https://github.com/nextcloud/documentserver_community/issues/24 , but after the most recent updates to ONLYOFFICE and the community document server I started getting a different error message `ONLYOFFICE not reachable. Contact your Administrator.'

I uninstalled and reinstalled both ONLYOFFICE and the community document server, clicked `save` in the ONLYOFFICE settings, and also did the  `chmod u+x docbuilder x2t` fix @tgurr described, but it didn't change anything. 

Here are the two most recent related logs:
```
[documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: not found
 at <<closure>>

 0. /config/www/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php line 64
    OCA\DocumentServer\Document\ConverterBinary->run("")
 1. /config/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php line 34
    OCA\DocumentServer\Document\ConverterBinary->test()
 2. /config/www/nextcloud/apps/documentserver_community/lib/Controller/StaticController.php line 89
    OCA\DocumentServer\SetupCheck->check()
 3. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\DocumentServer\Controller\StaticController->webApps("apps/api/documents/api.js")
 4. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\DocumentServ ... {}, "webApps")
 5. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "webApps")
 6. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\DocumentSe ... r", "webApps", OC\AppFramework\ ... {}, {path: "apps/api ... "})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({path: "apps/api ... "})
 8. /config/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {path: "apps/api ... "})
 9. /config/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/documents ... s")
10. /config/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /apps/documentserver_community/web-apps/apps/api/documents/api.js
from 172.19.0.1 by xthursdayx at 2020-01-29T21:25:24+00:00
```

```
[index] Error: Exception: trim() expects parameter 1 to be string, bool given at <<closure>>

0. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "webApps")
1. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\DocumentSe ... r", "webApps", OC\AppFramework\ ... {}, {path: "apps/api ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({path: "apps/api ... "})
3. /config/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {path: "apps/api ... "})
4. /config/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/documents ... s")
5. /config/www/nextcloud/index.php line 38
   OC::handleRequest()

GET /apps/documentserver_community/web-apps/apps/api/documents/api.js
from 172.19.0.1 by xthursdayx at 2020-01-29T21:25:51+00:00
```

**Comment by raminasgharian** [comment]
Community document server "not supported for this instance"
can't execute x2t binary, ensure php can execute binaries in the app folder
sh: ./x2t: Permission denied

I upgraded to 18/hub today and installed the OnlyOffice and Community Document Server apps but am greeted with an error when I try to open an existing or create a new document: "Community document server is not supported for this instance, please setup and configure an external document server"
I also give permission, but it returns to the previous state after the error.
$ chmod u+x docbuilder x2t

**Comment by Ramin1362** [comment]
Community document server "not supported for this instance"
can't execute x2t binary, ensure php can execute binaries in the app folder
sh: ./x2t: Permission denied

I upgraded to 18/hub today and installed the OnlyOffice and Community Document Server apps but am greeted with an error when I try to open an existing or create a new document: "Community document server is not supported for this instance, please setup and configure an external document server"
I also give permission, but it returns to the previous state after the error
$ chmod u+x docbuilder x2t

**Comment by marshalleq** [comment]
I'm also getting the ONLYOFFICE cannot be reached.  Please contact admin.  I've set the permissions of x2t as per above and still no luck.  It would be useful to know if this is DNS related or permissions related.  I suspect it's DNS related (or reverse proxy related) based on the below.

2020/01/29 20:31:06 [error] 347#347: *192092 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.3, server: _, request: "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "nextcloud.domain.com"
2020/02/06 10:25:19 [error] 347#347: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.3, server: _, request: "PROPFIND /remote.php/dav/files/9e40bcc8-5a53-1039-9f93-d18f70623e38/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "nextcloud.domain.com"
2020/02/09 17:44:25 [error] 346#346: *72 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.3, server: _, request: "GET /csrftoken HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "nextcloud.domain.com"

And the result of that is OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: not found

Nextcloud itself DOES resolve via my set up reverse proxy correctly, so unless there's an extra line needed for onlyoffice, but I assume they both communicate via the same web server over port 443.  It is only the onlyoffice instance that's not working, so there must be something basic I'm missing.  Also I assume the port 9000 above is some internal port that is set up for nextcloud / onlyoffice and doesn't need to be entered into the url anywhere...

BTW I'm using the linuxserver.io container...

**Comment by lalala119** [comment]
I got exactly same issue that xthursdayx has. Any hints?

**Comment by xthursdayx** [comment]
> I got exactly same issue that xthursdayx has. Any hints?

To my knowledge, this hasn’t been fixed. Or at least nothing I’ve done has fixed the issue.

**Comment by sean-sullivan1** [comment]
I'll throw my error into the party too hopefully someone can provide a fix. I did run the chmod command that @tgurr posted previously.

```
[documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: sh: ./x2t: not found
 at <<closure>>

 0. /config/www/nextcloud/apps/documentserver_community/lib/Document/ConverterBinary.php line 72
    OCA\DocumentServer\Document\ConverterBinary->run("")
 1. /config/www/nextcloud/apps/documentserver_community/lib/SetupCheck.php line 34
    OCA\DocumentServer\Document\ConverterBinary->test()
 2. /config/www/nextcloud/apps/documentserver_community/lib/Controller/StaticController.php line 89
    OCA\DocumentServer\SetupCheck->check()
 3. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\DocumentServer\Controller\StaticController->webApps("apps/api/documents/api.js")
 4. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\DocumentServ ... {}, "webApps")
 5. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "webApps")
 6. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\DocumentSe ... r", "webApps", OC\AppFramework\ ... {}, {path: "apps/api ... "})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({path: "apps/api ... "})
 8. /config/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {path: "apps/api ... "})
 9. /config/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/documents ... s")
10. /config/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /apps/documentserver_community/web-apps/apps/api/documents/api.js
from 40.142.6.210 by sean at 2020-02-14T15:15:21+00:00
```

**Comment by kesselb** [comment]
https://autoize.com/building-onlyoffice-document-server-from-source/ is a guide how to compile document server from source. Could someone try to recompile with muslc?

**Comment by wuast94** [comment]
I am using the actual nextcloud apache 18.xx version.. Onlyoffice working fine..the move to this container is a bit tricky but worked for me. 

But for someone how don't know that much about sysadmin should stay on Linux server version and wait for a working onlyoffice version I think

**Comment by xthursdayx** [comment]
I just updated to nc18.0.1, reinstalled both the Community Document Server and OnlyOffice, and applied @tgurr 's fix and am still getting the `./x2t: not found` error. However, I'm also getting a new linked error: `Exception: trim() expects parameter 1 to be string, bool given`. See the log below.

```
[index] Error: Exception: trim() expects parameter 1 to be string, bool given at <<closure>>

0. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\DocumentServ ... {}, "webApps")
1. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\DocumentSe ... r", "webApps", OC\AppFramework\ ... {}, {path: "apps/api ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({path: "apps/api ... "})
3. /config/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {path: "apps/api ... "})
4. /config/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/documents ... s")
5. /config/www/nextcloud/index.php line 38
   OC::handleRequest()

GET /apps/documentserver_community/web-apps/apps/api/documents/api.js
from 172.19.0.1 by xthursdayx at 2020-02-16T20:49:08+00:00
```

**Comment by Disco1** [comment]
For those on CentOS 7 / SELinux, beyond everything mentioned here, https://github.com/nextcloud/documentserver_community/issues/10#issuecomment-575935715

In nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/

`chcon --type httpd_sys_script_exec_t *.so.58`
`chcon --type httpd_sys_script_exec_t *.so`

**Comment by anatomism** [comment]
> For those on CentOS 7 / SELinux, do this first: [#10 (comment)](https://github.com/nextcloud/documentserver_community/issues/10#issuecomment-575935715)
> 
> ... then, in nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/
> 
> `chcon --type httpd_sys_script_exec_t *.so.58`
> `chcon --type httpd_sys_script_exec_t *.so`

This worked for me when trying to view on mobile app, however as with the above (and comment 10) I had to also include the binary, x2t, so the following was done for me to make it work

`cd <nextcloud_root_folder>/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/`

`chmod u+x docbuilder x2t`
`setsebool -P httpd_unified 1`
`ausearch -c 'x2t' --raw | audit2allow -M my-x2t`
`semodule -i my-x2t.pp`

`chcon --type httpd_sys_script_exec_t *.so.58`
`chcon --type httpd_sys_script_exec_t *.so`
`chcon --type httpd_sys_script_exec_t x2t`

My install is CentOS 7 latest with SELinux enabled

**Comment by NoxInmortus** [comment]
Hello, there seems to be no reports from Nextcloud or DocumentServer staff here about the resolution of this issue. Does it progress in any way?

**Comment by skjnldsv** [comment]
Please also remember that the files needs to be owned by the html user (www-data usually, adjust to your setup)

**Comment by siccovansas** [comment]
For those who use an alpine Nextcloud image in their docker compose (which I had because Nextcloud uses alpine in their docker compose example code), you can switch to using the non-alpine Nextcloud image. That way I got Onlyoffice to work.

As always, make sure you have backups!

- Remove the `-alpine` part from the nextcloud service in your `docker-compose.yml`
- Run `docker-compose pull`
- Run `docker-compose up -d`
- Change ownership permissions as alpine uses a different user id (change `nextcloud_app_1` to your container name if it is different): `docker exec nextcloud_app_1 chown -R www-data:root /var/www`
- You might need to do a docker-compose restart and/or reinstall the community document server and ONLYOFFICE apps

**Comment by gfiasco** [comment]
I have tried everything in here but nothing seem to work around this

I'm using nextcloud:stable with mysql as db.

even fresh installation suffers of this

**Comment by oucil** [comment]
> setsebool -P httpd_unified 1

If anyone read this above with reference to CentOS and is serious about using SELinux properly, **DO NOT** do this, as it essentially tells SELinux to stop enforcing anything for httpd effectively giving it all permissions for any resources assigned to the Apache user.  Do a little more work and figure out what specific contexts / boolean permissions you need and enable them, and only them.  If you're using `php_fpm`, you can further isolate your permissions using sub-contexts, and different apache child users.

**Comment by zynexiz** [comment]
As stated above, don't disable selniux to enforce it's policy's. The sever needs to execute the binary, so instead add the following (might have to change the path to your installation folder) for CentOS;

```
semanage fcontext -a -t httpd_sys_script_exec_t '/var/www/html/nextcloud/apps/documentserver_community/3rdparty/onlyoffice/documentserver(/.*)?'
restorecon -R -v /var/www/html/nextcloud
```

**Comment by yardbro** [comment]
Old thread but to anyone still experiencing this issue, ensure that you use -R when applying chown (**chown -R www-data:www-data documentserver_community/**) if you installed the Community Document Server app manually. I had this exact issue and realized that I had only been changing ownership of the main directory, not the sub-directories. Hope this helps someone

**Comment by deajan** [comment]
For whoever might be concerned about the more recent problems with x2t and onlyoffice, eg `OCA\DocumentServer\Document\DocumentConversionException: ./x2t: error while loading shared libraries: libgraphics.so: cannot open shared object file: No such file or directory`

Check if your problem is SELinux related, eg disable selinux with `setenforce 0` and try again.
If so, re-enable selinux with `setenforce 1` and proceed to create the following Selinux policy:

Create file `/root/my-onlyoffice.te` containing
```

module my-onlyoffice 1.0;

require {
        type httpd_sys_script_exec_t;
        type httpd_t;
        type ld_so_t;
        type configfs_t;
        class file { execute_no_trans setattr };
        class dir { getattr };
}

#============= httpd_sys_script_exec_t ==============
allow httpd_t httpd_sys_script_exec_t:file setattr;
allow httpd_t ld_so_t:file execute_no_trans;
allow httpd_t configfs_t:dir getattr;
```

Now proceed to create a module from that file with command
```
checkmodule -M -m -o /root/my-onlyoffice.mod /root/my-onlyoffice.te
```

Now create a selinux loadable policy
```
semodule_package -o /root/my-onlyoffice.pp -m /root/my-onlyoffice.mod
```

Load the policy with `cd /root && semodule -i my-onlyoffice.pp`

Now it's time to label your nextcloud + onlyoffice setup (of course, adapt paths to your virtualhost)
```
# php specific session, tmp and opcache dirs
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/tmp(/.*)?'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/sessions(/.*)?'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/opcache(/.*)?'
# nextcloud data dir
semanage fcontext -a -t httpd_sys_rw_content_t '/data(/.*)?'
# nextcloud app
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/ftp/www/config(/.*)?'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/ftp/www/apps(/.*)?'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/ftp/www/.htaccess'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/ftp/www/.user.ini'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/nextcloud/ftp/www/3rdparty/aws/aws-sdk-php/src/data/logs(/.*)?'
# onlyoffice specific
semanage fcontext -a -t httpd_sys_script_exec_t '/var/www/nextcloud/ftp/www/apps/documentserver_community/3rdparty/onlyoffice/documentserver(/.*)?'
semanage fcontext -a -t ld_so_t '/var/www/nextcloud/ftp/www/apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/FileConverter/bin/.*\.so.*'
# apply above contexts
restorecon -Rv '/var/www/nextcloud/'
restorecon -Rv '/data'
```

Should work ;)

**Comment by Wotisrv** [comment]
I was running OnlyOffice fine since it was included in Nextcloud 19. I needed to adjust the SELinux permissions as described here to get it work.
Now for a couple of days I figured out that I got back the x2t permission denied error. The solution from @deajan fixed the error. 
Furthermore I needed to issue `chmod u+x docbuilder` since this one lost its permissions.
After all that, I can run OnlyOffice inside Nextcloud but with the mobile app I got still x2t permission denied error.
Everything works fine with disabled SELinux.
I upgraded also to Nextcloud 20.0.2 today, but permission error using mobile app still continues.
No log in SELinux about blocking but in Nextcloud.

System Fedora-Server 32 Edition, Nextcloud 20.0.2

**Comment by AndreasDekiert** [comment]
Even after applying @deajan 's SELinux module and contexts I still cannot get OnlyOffice to run. Checking the SELinux audits with `ausearch -c 'x2t'` I get several results like the following:  
`type=ANOM_ABEND msg=audit(1615135507.682:588047): audit=982 uid=982 gid=975 ses=82515 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=18453 comm="x2t" reason="memory violation" sig=4`  

Creating a custom SELinux module with `audit2allow` is not possible for this "memory violation". Any ideas?

System CentOS 7, Nextcloud 20.0.8

**Comment by Wotisrv** [comment]
I applied @deajan SELinux module and I get now: 
"SELinux prevents php-fpm from accessing sock_file clamd.sock with write access."
type=AVC msg=audit(1615235215.940:543): avc: denied { write } for pid=1097 comm="php-fpm" name="clamd.sock" dev="tmpfs" ino=1812 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:antivirus_var_run_t:s0 tclass=sock_file permissive=0 
I do not understand why php-fpm should get write access to clamd.sock file?
The SELinux policy allow antivirus to can scan system is activated: 
boolean -m -1 antivirus_can_scan_system

System Fedora 33 Server-Edition, Nextcloud 20.0.8

**Comment by deajan** [comment]
@Wotisrv Looks like you have the antivirus plugin in Nextcloud where nextcloud itself triggers an AV scan. Can you confirm ?

**Comment by Wotisrv** [comment]
@deajan yes that's right.

**Comment by tiehfood** [comment]
I could successfully get Documentcommunity-Server and Nextcloud (21) running in an alpine container with help of https://github.com/sgerrand/alpine-pkg-glibc and some tweaks. Someone interested?

**Comment by jastab** [comment]
On our server (managed by the provider) the same issue comes up (since yesterday). Error messages: 
"Community document server is not supported for this instance, please setup and configure an external document server✖" and:
"can't execute x2t binary, ensure php can execute binaries in the app folder✖"
Running Nextcloud 21.0.1
Reinstalling both Apps didn't resolve the issue. 

Since I have no admin access to the server itself i can't provide much more information. The provider claims it gives no support for the App but tells me, that other customers experience the same issue. 

Bottonline: Issue is still unresolved and comes up under Nexcloud 21 as well.

**Comment by sich97** [comment]
Yeah I just got this error as well. I've read about the "chmod u+x docbuilder" solution, but I don't have a file path which corresponds to the where I'm supposed to run that command.
Under "<nextcloud_root_folder>/apps/documentserver_community/3rdparty/onlyoffice/documentserver/", I only have a folder called "web-apps".
This should be looked into more, since this was a fresh install. I installed nextcloud manually (not docker), but I installed OnlyOffice and Community Document Server through Nexctloud's App menu. So if I'm missing any dependencies then at least I should have been informed of such in the documentation or after setup. But of course the best thing would be if the app itself was plug and play.

**Comment by frafor1988** [comment]
Same issue here
